openapi: 3.0.0
info:
  title: input API
  description: API to demonstrate a single POST route with OpenAPI specification.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /input:
    post:
      summary: input data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - value
              properties:
                name:
                  type: string
                  description: The name associated with the data.
                  default:  people_around_Sensor
                labels:
                  type: array
                  description: An array of labels, each with its own value.
                  items:
                    type: object
                    required:
                      - name
                      - value
                    properties:
                      name:
                        type: string
                        description: The name of the label
                        default: location
                      value:
                        type: string
                        description: The value associated with this label.
                        default: Pizza_Station
                value:
                  type: float
                  default: 10.2
                  description: float value of the metric
      responses:
        '200':
          description: Data successfully received.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid input received.