name: deploy to github container
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - run: ls
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        file: dockerfile
        push: true
        tags: ghcr.io/mari0theminer/Hackathon_2024_HN_TEAM-input-api:latest, ghcr.io/mari0theminer/Hackathon_2024_HN_TEAM-input-api:${{ github.run_number }}
              
