name: deploy to github container

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: ./inputAPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la    
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          context: ./inputAPI
          tags: |
            ghcr.io/mari0theminer/hackathon_2024_hn_team-input-api:latest
            ghcr.io/mari0theminer/hackathon_2024_hn_team-input-api:${{ github.run_number }}
